kind: pipeline
name: lang

steps:
  - name: test
    image: node
    commands:
      - npm install
      - cd sdk
      - npm install
      - cd ..
      - npm run test:sunit
---
kind: pipeline
name: built-cli
steps:
  - name: build-and-test
    image: node
    commands:
      - npm install
      - npm run build:cli
      - cd cli
      - npm install
      - npm test
---
kind: pipeline
name: installable-cli
steps:
  - name: install-and-test
    image: node
    environment:
      AMBER_CLI: amber
    commands:
      - cd cli
      - npm install
      - npm install -g @ambers/cli
      - npm test
