language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "node"
install:
  - npm install -g grunt-cli mocha
  - npm install
  - cd external/amber-cli
  - npm install
  - cd ../sdk
  - npm install
  - cd ../..
script:
  - npm test
  - cd external/amber-cli
  - npm install -g amber-cli
  - AMBER_CLI=amber npm test
  - npm install -g amber-cli@bleedingedge
  - AMBER_CLI=amber npm test
  - cd ../..
